# ------ root_path/dataset_name ------
root_path: '/home/user/FewShot/TipAdapter/data'


# ------ Load Cache and Features ------
load_cache: False
load_pre_feat: False

# load_cache: True
# load_pre_feat: True


# ------ Hyperparamters ------
search_hp: True
# search_hp: False

search_scale: [20, 10]
search_step: [200, 20]

init_beta: 1
init_alpha: 3


# ------ Basic Config ------
dataset: 'cars'
shots: 1
backbone: 'ViT-B/16'

lr: 0.001
augment_epoch: 10
train_epoch: 50